const LOGIN_STATUS = 'LOGIN_STATUS';
const LANGUAGE = 'LANGUAGE';
const PAGE_SIZE = 'PAGE_SIZE';
const SET_LANGUAGE = 'SET_LANGUAGE';
export {
  LOGIN_STATUS,
  LANGUAGE,
  PAGE_SIZE,
  SET_LANGUAGE,
};
